#!/usr/bin/env python3
"""Describe the blobs a firmware build goes with: the two iCE40 gateware images and the
ESP32-C3 esp-hosted image, which the pod keeps in W25Q slots (src/blob_store.h) rather than in
its internal flash.

Writes, for the firmware and for whoever installs it (release CI, benchpod CLI, server):
  <out-dir>/gw0.bin, gw1.bin, esp.bin   the blobs, under their slot names
  <out-dir>/manifest.json               size, SHA-256 and gateware version of each
  <header>                              the same as C, compiled into the firmware so the pod
                                        knows which blobs it was built and tested with

A missing input (a build without gateware) is written as size 0: the firmware then reports
that slot's expected blob as unknown instead of failing the build.
"""
import argparse
import hashlib
import json
import os
import shutil


def describe(name, path, version):
    if not path or not os.path.isfile(path):
        return {"name": name, "file": None, "size": 0, "sha256": "", "version": version}
    data = open(path, "rb").read()
    return {
        "name": name,
        "file": name + ".bin",
        "size": len(data),
        "sha256": hashlib.sha256(data).hexdigest(),
        "version": version,
    }


def c_bytes(hexdigest):
    if not hexdigest:
        return "{0}"
    return "{" + ", ".join("0x" + hexdigest[i:i + 2] for i in range(0, 64, 2)) + "}"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--gw0", help="gateware image 0 (closed loop)")
    ap.add_argument("--gw1", help="gateware image 1 (deep replay)")
    ap.add_argument("--esp", help="ESP32-C3 esp-hosted merged image")
    ap.add_argument("--gw-version", type=int, default=0, help="GATEWARE_VERSION of both images")
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--header", required=True)
    a = ap.parse_args()

    entries = [
        (describe("gw0", a.gw0, a.gw_version), a.gw0),
        (describe("gw1", a.gw1, a.gw_version), a.gw1),
        (describe("esp", a.esp, 0), a.esp),
    ]

    os.makedirs(a.out_dir, exist_ok=True)
    for e, src in entries:
        if e["file"]:
            shutil.copyfile(src, os.path.join(a.out_dir, e["file"]))
    manifest = {"format": 1, "gateware_version": a.gw_version, "blobs": [e for e, _ in entries]}
    with open(os.path.join(a.out_dir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")

    lines = [
        "/* Generated by tools/blob_manifest.py: the blobs this firmware was built with. */",
        "#ifndef BLOB_MANIFEST_GEN_H",
        "#define BLOB_MANIFEST_GEN_H",
        "#define BLOB_MANIFEST_GW_VERSION %du" % a.gw_version,
        "#define BLOB_MANIFEST_INIT { \\",
    ]
    for e, _ in entries:
        lines.append("    { %du, %du, %s }, \\" % (e["size"], e["version"], c_bytes(e["sha256"])))
    lines += ["}", "#endif", ""]
    with open(a.header, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
