#!/usr/bin/env bash
#
# gen_cloud_ca.sh — regenerate src/cloud_ca.h, the trust anchors embedded in the
# STM32 firmware for verifying the outbound WSS cloud connection.
#
# The server (www.embeddedci.com) uses Let's Encrypt, so the trust anchors are
# the two ISRG roots (X1 = RSA, X2 = ECDSA). Pass one or more PEM files holding
# the root cert(s) you want to embed; defaults to extracting the ISRG roots from
# the system/openssl CA bundle if none are given.
#
# Usage:
#   tools/gen_cloud_ca.sh [root1.pem root2.pem ...]   > /dev/null   # writes src/cloud_ca.h
#
# Keep this small (each embedded root costs ~2 KB RAM as a live x509_crt at
# config time) — embed only the roots the server actually chains to.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="src/cloud_ca.h"

pems=("$@")
if [ ${#pems[@]} -eq 0 ]; then
  # Pull the ISRG roots out of openssl's default bundle into temp files.
  bundle="$(openssl version -d | sed 's/.*"\(.*\)"/\1/')/cert.pem"
  [ -f "$bundle" ] || bundle="/etc/ssl/cert.pem"
  for label in "ISRG Root X1" "ISRG Root X2"; do
    tmp="$(mktemp)"
    awk -v lbl="$label" '
      $0 ~ lbl {f=1}
      f && /-----BEGIN CERTIFICATE-----/{p=1}
      p{print}
      p && /-----END CERTIFICATE-----/{exit}
    ' "$bundle" > "$tmp"
    [ -s "$tmp" ] || { echo "could not find \"$label\" in $bundle" >&2; exit 1; }
    pems+=("$tmp")
  done
fi

{
  cat <<'HDR'
#ifndef CLOUD_CA_H
#define CLOUD_CA_H

/* Trust anchors for the outbound WSS cloud client (www.embeddedci.com).
 *
 * The server cert chains:  embeddedci.com  ->  Let's Encrypt E-series
 * intermediate  ->  ISRG Root X1.  Both Let's Encrypt roots are embedded so
 * verification survives a future chain switch (X1 = RSA, X2 = ECDSA).
 *
 * Generated by tools/gen_cloud_ca.sh from a CA bundle — do not hand-edit.
 * Passed to altcp_tls_create_config_client(); the length MUST include the
 * trailing NUL (mbedTLS PEM parsing requires it). Used only when cfg.verify=1.
 */
static const unsigned char cloud_ca_pem[] =
HDR
  for f in "${pems[@]}"; do
    # Emit only the PEM block(s), each source line as a quoted C string with \n.
    awk '/-----BEGIN CERTIFICATE-----/{p=1} p{print} /-----END CERTIFICATE-----/{p=0}' "$f" \
      | sed 's/\r$//' | sed 's/.*/"&\\n"/'
  done
  echo ";"
  cat <<'FTR'

/* Length includes the terminating NUL (required by mbedtls_x509_crt_parse for PEM). */
static const unsigned int cloud_ca_pem_len = sizeof(cloud_ca_pem);

#endif /* CLOUD_CA_H */
FTR
} > "$OUT"

echo "wrote $OUT ($(grep -c 'BEGIN CERTIFICATE' "$OUT") cert(s))" >&2
